apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: hello-world-stage
  namespace: argocd

  annotations:

    argocd-image-updater.argoproj.io/image-list: hello=ghcr.io/hiteshguptagt/hello-spring

    argocd-image-updater.argoproj.io/hello.update-strategy: newest-build

    argocd-image-updater.argoproj.io/write-back-method: git

    argocd-image-updater.argoproj.io/git-branch: main

    argocd-image-updater.argoproj.io/git-repository: https://github.com/hiteshguptagt/hello-world-gitops.git

    argocd-image-updater.argoproj.io/git-credentials-secret: git-creds

spec:
  project: default

  source:
    repoURL: https://github.com/hiteshguptagt/hello-world-gitops.git
    targetRevision: main
    path: workloads/hello-world/overlays/stage

  destination:
    server: https://kubernetes.default.svc
    namespace: hello-stage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
